/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_AdbSetting */


JNIEXPORT jint JNICALL Java_com_android_settings_AdbSetting_getHashcode
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jstring JNICALL Java_com_android_settings_AdbSetting_getRandomString
  (JNIEnv *, jobject, jint);
